import { Perk } from "../interfaces";

export const perks: Array<Perk> = [
    'Axe',
    'Blunt',
    'SmallBlunt',
    'LongBlade',
    'SmallBlade',
    'Spear',
    'Maintenance',
    'Aiming',
    'Reloading',
    'Woodwork',
    'Cooking',
    'Farming',
    'Doctor',
    'Electricity',
    'MetalWelding',
    'Mechanics',
    'Tailoring',
    'Fishing',
    'Trapping',
    'PlantScavenging',
    'Fitness',
    'Strength',
    'Sprinting',
    'Lightfoot',
    'Nimble',
    'Sneak'
];